2020-01-29 14:11:36,185 p=26718 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/os_test/ymsl-test17 as an inventory source

2020-01-29 14:11:36,186 p=26718 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:11:36,188 p=26718 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:11:36,277 p=26718 u=tsunatori |  ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml': line 3, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Ansibleでsetup可能か確認
      setup:
           ^ here

2020-01-29 14:13:41,462 p=26867 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:13:41,463 p=26867 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:13:41,465 p=26867 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:13:41,569 p=26867 u=tsunatori |  ERROR! the role 'windows-setting' was not found in /home/tsunatori/git/ansible/defaultdir/roles:/home/tsunatori/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/tsunatori/git/ansible/defaultdir

The error appears to have been in '/home/tsunatori/git/ansible/defaultdir/site.yml': line 24, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      import_role:
        name: windows-setting
              ^ here

2020-01-29 14:17:58,128 p=27087 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:17:58,128 p=27087 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:17:58,130 p=27087 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:17:58,220 p=27087 u=tsunatori |  ERROR! the role 'windows-setting' was not found in /home/tsunatori/git/ansible/defaultdir/roles:/home/tsunatori/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/tsunatori/git/ansible/defaultdir

The error appears to have been in '/home/tsunatori/git/ansible/defaultdir/site.yml': line 24, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      import_role:
        name: windows-setting
              ^ here

2020-01-29 14:18:57,180 p=27154 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:18:57,180 p=27154 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:18:57,183 p=27154 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:18:57,272 p=27154 u=tsunatori |  ERROR! the role 'windows-setting' was not found in /home/tsunatori/git/ansible/defaultdir/roles:/home/tsunatori/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/tsunatori/git/ansible/defaultdir

The error appears to have been in '/home/tsunatori/git/ansible/defaultdir/site.yml': line 24, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      import_role:
        name: windows-setting
              ^ here

2020-01-29 14:20:47,616 p=27261 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:20:47,616 p=27261 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:20:47,618 p=27261 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:20:47,631 p=27261 u=tsunatori |  ERROR! Unable to retrieve file contents
Could not find or access '/home/tsunatori/git/ansible/defaultdir/TEST_connection.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
2020-01-29 14:21:04,607 p=27286 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:21:04,608 p=27286 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:21:04,610 p=27286 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:21:04,700 p=27286 u=tsunatori |  ERROR! the role 'windows-setting' was not found in /home/tsunatori/git/ansible/defaultdir/roles:/home/tsunatori/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/tsunatori/git/ansible/defaultdir

The error appears to have been in '/home/tsunatori/git/ansible/defaultdir/test.yml': line 25, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      import_role:
        name: windows-setting
              ^ here

2020-01-29 14:21:14,902 p=27305 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:21:14,902 p=27305 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:21:14,904 p=27305 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:21:14,993 p=27305 u=tsunatori |  ERROR! the role 'windows-setting' was not found in /home/tsunatori/git/ansible/defaultdir/roles:/home/tsunatori/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/tsunatori/git/ansible/defaultdir

The error appears to have been in '/home/tsunatori/git/ansible/defaultdir/test.yml': line 25, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      import_role:
        name: windows-setting
              ^ here

2020-01-29 14:22:04,095 p=27356 u=tsunatori |   [WARNING]: Unable to parse /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test17 as an inventory source

2020-01-29 14:22:04,095 p=27356 u=tsunatori |   [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-29 14:22:04,097 p=27356 u=tsunatori |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2020-01-29 14:22:04,435 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:22:04,439 p=27356 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:22:04,440 p=27356 u=tsunatori |  skipping: no hosts matched
2020-01-29 14:22:04,443 p=27356 u=tsunatori |  PLAY [DeepSecurityエージェントのインストール] *************************************************************************************************
2020-01-29 14:22:04,443 p=27356 u=tsunatori |  skipping: no hosts matched
2020-01-29 14:22:04,443 p=27356 u=tsunatori |  PLAY RECAP ***********************************************************************************************************************
2020-01-29 14:22:16,796 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:22:16,802 p=27386 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:22:20,711 p=27386 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:22:20,721 p=27386 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:22:20,833 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:22:20,975 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:22:20,986 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:22:21,214 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:22:24,045 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:22:24,053 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:22:24,064 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:22:24,069 p=27386 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:22:26,594 p=27386 u=tsunatori |  Perform task: TASK: /usr/bin/python26 でセットアップ可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************
2020-01-29 14:22:28,159 p=27386 u=tsunatori |  Perform task: TASK: redhat-releaseからバージョンを確認 (N)o/(y)es/(c)ontinue: **************************************************************
2020-01-29 14:22:28,167 p=27386 u=tsunatori |  TASK [redhat-releaseからバージョンを確認] **************************************************************************************************
2020-01-29 14:22:28,184 p=27386 u=tsunatori |  fatal: [10.147.5.251]: FAILED! => {"msg": "The conditional check 'check_setup is failed' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to have been in '/home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml': line 19, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      block:\n        - name: redhat-releaseからバージョンを確認\n          ^ here\n"}
2020-01-29 14:22:28,185 p=27386 u=tsunatori |  	to retry, use: --limit @/home/tsunatori/git/ansible/defaultdir/site.retry

2020-01-29 14:22:28,185 p=27386 u=tsunatori |  PLAY RECAP ***********************************************************************************************************************
2020-01-29 14:22:28,185 p=27386 u=tsunatori |  10.147.5.251               : ok=1    changed=0    unreachable=0    failed=1   
2020-01-29 14:22:36,718 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:22:36,724 p=27418 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:22:41,410 p=27418 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:22:41,419 p=27418 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:22:41,532 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:22:41,666 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:22:41,678 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:22:41,892 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:22:44,586 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:22:44,594 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:22:44,605 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:22:44,611 p=27418 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:22:45,500 p=27418 u=tsunatori |  Perform task: TASK: /usr/bin/python26 でセットアップ可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************
2020-01-29 14:22:45,508 p=27418 u=tsunatori |  TASK [/usr/bin/python26 でセットアップ可能か確認] ********************************************************************************************
2020-01-29 14:22:45,522 p=27418 u=tsunatori |  fatal: [10.147.5.251]: FAILED! => {"msg": "The conditional check 'check_setup is failed' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to have been in '/home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml': line 12, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: /usr/bin/python26 でセットアップ可能か確認\n      ^ here\n"}
2020-01-29 14:22:45,523 p=27418 u=tsunatori |  ...ignoring
2020-01-29 14:23:12,793 p=27418 u=tsunatori |  Perform task: TASK: redhat-releaseからバージョンを確認 (N)o/(y)es/(c)ontinue: **************************************************************
2020-01-29 14:23:12,801 p=27418 u=tsunatori |  TASK [redhat-releaseからバージョンを確認] **************************************************************************************************
2020-01-29 14:23:12,816 p=27418 u=tsunatori |  fatal: [10.147.5.251]: FAILED! => {"msg": "The conditional check 'check_setup is failed' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to have been in '/home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml': line 19, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      block:\n        - name: redhat-releaseからバージョンを確認\n          ^ here\n"}
2020-01-29 14:23:12,817 p=27418 u=tsunatori |  	to retry, use: --limit @/home/tsunatori/git/ansible/defaultdir/site.retry

2020-01-29 14:23:12,817 p=27418 u=tsunatori |  PLAY RECAP ***********************************************************************************************************************
2020-01-29 14:23:12,818 p=27418 u=tsunatori |  10.147.5.251               : ok=2    changed=0    unreachable=0    failed=1   
2020-01-29 14:24:10,951 p=27514 u=tsunatori |  ansible-playbook 2.7.0
  config file = /home/tsunatori/git/ansible/defaultdir/ansible.cfg
  configured module search path = [u'/home/tsunatori/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
2020-01-29 14:24:10,951 p=27514 u=tsunatori |  Using /home/tsunatori/git/ansible/defaultdir/ansible.cfg as config file
2020-01-29 14:24:10,951 p=27514 u=tsunatori |  setting up inventory plugins
2020-01-29 14:24:10,967 p=27514 u=tsunatori |  Parsed /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test017 inventory source with ini plugin
2020-01-29 14:24:11,060 p=27514 u=tsunatori |  statically imported: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml
2020-01-29 14:24:11,070 p=27514 u=tsunatori |  Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
2020-01-29 14:24:11,273 p=27514 u=tsunatori |  PLAYBOOK: site.yml ***************************************************************************************************************
2020-01-29 14:24:11,274 p=27514 u=tsunatori |  2 plays in site.yml
2020-01-29 14:24:11,303 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:24:11,309 p=27514 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:24:11,312 p=27514 u=tsunatori |  META: ran handlers
2020-01-29 14:24:13,650 p=27514 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:24:13,659 p=27514 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:24:13,659 p=27514 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:2
2020-01-29 14:24:13,765 p=27514 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:24:13,766 p=27514 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:24:13,770 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:24:13,883 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:24:13,885 p=27514 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:24:13,893 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:24:14,131 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:24:16,821 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6899
2020-01-29 14:24:16,829 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:24:16,839 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:24:16,844 p=27514 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:24:22,775 p=27514 u=tsunatori |  Perform task: TASK: /usr/bin/python26 でセットアップ可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************
2020-01-29 14:24:26,055 p=27514 u=tsunatori |  Perform task: TASK: redhat-releaseからバージョンを確認 (N)o/(y)es/(c)ontinue: **************************************************************
2020-01-29 14:24:26,916 p=27514 u=tsunatori |  Perform task: TASK: RHEL5系であることを確認 (N)o/(y)es/(c)ontinue: ************************************************************************
2020-01-29 14:24:27,519 p=27514 u=tsunatori |  Perform task: TASK: EPELをインストール (N)o/(y)es/(c)ontinue: ***************************************************************************
2020-01-29 14:24:28,068 p=27514 u=tsunatori |  Perform task: TASK: python26をインストール (N)o/(y)es/(c)ontinue: ***********************************************************************
2020-01-29 14:24:28,776 p=27514 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能になっていることを確認 (N)o/(y)es/(c)ontinue: ************************************************************
2020-01-29 14:24:29,477 p=27514 u=tsunatori |  Perform task: TASK: ansible_python_interpreter変数に/usr/bin/python26を設定 (N)o/(y)es/(c)ontinue: *************************************
2020-01-29 14:24:30,394 p=27514 u=tsunatori |  Perform task: TASK: SELinuxの状態を確認 (N)o/(y)es/(c)ontinue: *************************************************************************
2020-01-29 14:24:31,333 p=27514 u=tsunatori |  Perform task: TASK: debug (N)o/(y)es/(c)ontinue: *********************************************************************************
2020-01-29 14:24:32,456 p=27514 u=tsunatori |  Perform task: TASK: SELinuxが無効またはAnsibleから操作可能でない場合はPlaybookを失敗させる (N)o/(y)es/(c)ontinue: ****************************************
2020-01-29 14:24:32,457 p=27514 u=tsunatori |  META: ran handlers
2020-01-29 14:24:32,457 p=27514 u=tsunatori |  META: ran handlers
2020-01-29 14:24:32,463 p=27514 u=tsunatori |  PLAY [DeepSecurityエージェントのインストール] *************************************************************************************************
2020-01-29 14:24:36,777 p=27514 u=tsunatori |  Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************
2020-01-29 14:24:36,777 p=27514 u=tsunatori |  META: ran handlers
2020-01-29 14:24:36,778 p=27514 u=tsunatori |  META: ran handlers
2020-01-29 14:24:36,778 p=27514 u=tsunatori |  META: ran handlers
2020-01-29 14:24:36,779 p=27514 u=tsunatori |  PLAY RECAP ***********************************************************************************************************************
2020-01-29 14:24:36,779 p=27514 u=tsunatori |  10.147.5.251               : ok=1    changed=0    unreachable=0    failed=0   
2020-01-29 14:24:40,070 p=27552 u=tsunatori |  ansible-playbook 2.7.0
  config file = /home/tsunatori/git/ansible/defaultdir/ansible.cfg
  configured module search path = [u'/home/tsunatori/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
2020-01-29 14:24:40,071 p=27552 u=tsunatori |  Using /home/tsunatori/git/ansible/defaultdir/ansible.cfg as config file
2020-01-29 14:24:40,071 p=27552 u=tsunatori |  setting up inventory plugins
2020-01-29 14:24:40,086 p=27552 u=tsunatori |  Parsed /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test017 inventory source with ini plugin
2020-01-29 14:24:40,177 p=27552 u=tsunatori |  statically imported: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml
2020-01-29 14:24:40,187 p=27552 u=tsunatori |  Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
2020-01-29 14:24:40,387 p=27552 u=tsunatori |  PLAYBOOK: site.yml ***************************************************************************************************************
2020-01-29 14:24:40,388 p=27552 u=tsunatori |  2 plays in site.yml
2020-01-29 14:24:40,416 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:24:40,423 p=27552 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:24:40,425 p=27552 u=tsunatori |  META: ran handlers
2020-01-29 14:24:41,520 p=27552 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:24:41,528 p=27552 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:24:41,529 p=27552 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:2
2020-01-29 14:24:41,636 p=27552 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:24:41,637 p=27552 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:24:41,641 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:24:41,744 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:24:41,745 p=27552 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:24:41,754 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:24:41,910 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:24:44,369 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:24:44,377 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:24:44,388 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:24:44,393 p=27552 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:24:45,393 p=27552 u=tsunatori |  Perform task: TASK: /usr/bin/python26 でセットアップ可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************
2020-01-29 14:24:45,401 p=27552 u=tsunatori |  TASK [/usr/bin/python26 でセットアップ可能か確認] ********************************************************************************************
2020-01-29 14:24:45,401 p=27552 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:12
2020-01-29 14:24:45,415 p=27552 u=tsunatori |  fatal: [10.147.5.251]: FAILED! => {
    "msg": "The conditional check 'check_setup is failed' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to have been in '/home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml': line 12, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: /usr/bin/python26 でセットアップ可能か確認\n      ^ here\n"
}
2020-01-29 14:24:45,415 p=27552 u=tsunatori |  ...ignoring
2020-01-29 14:25:11,232 p=27552 u=tsunatori |   [ERROR]: User interrupted execution

2020-01-29 14:26:19,309 p=27650 u=tsunatori |  ansible-playbook 2.7.0
  config file = /home/tsunatori/git/ansible/defaultdir/ansible.cfg
  configured module search path = [u'/home/tsunatori/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
2020-01-29 14:26:19,309 p=27650 u=tsunatori |  Using /home/tsunatori/git/ansible/defaultdir/ansible.cfg as config file
2020-01-29 14:26:19,310 p=27650 u=tsunatori |  setting up inventory plugins
2020-01-29 14:26:19,325 p=27650 u=tsunatori |  Parsed /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test017 inventory source with ini plugin
2020-01-29 14:26:19,418 p=27650 u=tsunatori |  statically imported: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml
2020-01-29 14:26:19,429 p=27650 u=tsunatori |  Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
2020-01-29 14:26:19,632 p=27650 u=tsunatori |  PLAYBOOK: site.yml ***************************************************************************************************************
2020-01-29 14:26:19,633 p=27650 u=tsunatori |  2 plays in site.yml
2020-01-29 14:26:19,662 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:26:19,668 p=27650 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:26:19,671 p=27650 u=tsunatori |  META: ran handlers
2020-01-29 14:26:20,990 p=27650 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:26:20,999 p=27650 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:26:20,999 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:2
2020-01-29 14:26:21,110 p=27650 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:26:21,111 p=27650 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:26:21,115 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:26:21,237 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:26:21,238 p=27650 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:26:21,249 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:26:21,679 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:26:24,471 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:26:24,480 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:26:24,496 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:26:24,501 p=27650 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:26:25,535 p=27650 u=tsunatori |  Perform task: TASK: /usr/bin/python26 でセットアップ可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************
2020-01-29 14:26:25,543 p=27650 u=tsunatori |  TASK [/usr/bin/python26 でセットアップ可能か確認] ********************************************************************************************
2020-01-29 14:26:25,543 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:12
2020-01-29 14:26:25,557 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:26,714 p=27650 u=tsunatori |  Perform task: TASK: redhat-releaseからバージョンを確認 (N)o/(y)es/(c)ontinue: **************************************************************
2020-01-29 14:26:26,722 p=27650 u=tsunatori |  TASK [redhat-releaseからバージョンを確認] **************************************************************************************************
2020-01-29 14:26:26,722 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:19
2020-01-29 14:26:26,736 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:27,374 p=27650 u=tsunatori |  Perform task: TASK: RHEL5系であることを確認 (N)o/(y)es/(c)ontinue: ************************************************************************
2020-01-29 14:26:27,382 p=27650 u=tsunatori |  TASK [RHEL5系であることを確認] ************************************************************************************************************
2020-01-29 14:26:27,382 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:24
2020-01-29 14:26:27,395 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:27,860 p=27650 u=tsunatori |  Perform task: TASK: EPELをインストール (N)o/(y)es/(c)ontinue: ***************************************************************************
2020-01-29 14:26:27,868 p=27650 u=tsunatori |  TASK [EPELをインストール] ***************************************************************************************************************
2020-01-29 14:26:27,868 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:28
2020-01-29 14:26:27,881 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:28,311 p=27650 u=tsunatori |  Perform task: TASK: python26をインストール (N)o/(y)es/(c)ontinue: ***********************************************************************
2020-01-29 14:26:28,318 p=27650 u=tsunatori |  TASK [python26をインストール] ***********************************************************************************************************
2020-01-29 14:26:28,319 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:35
2020-01-29 14:26:28,332 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:28,856 p=27650 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能になっていることを確認 (N)o/(y)es/(c)ontinue: ************************************************************
2020-01-29 14:26:28,864 p=27650 u=tsunatori |  TASK [Ansibleでsetup可能になっていることを確認] ************************************************************************************************
2020-01-29 14:26:28,864 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:38
2020-01-29 14:26:28,877 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:29,480 p=27650 u=tsunatori |  Perform task: TASK: ansible_python_interpreter変数に/usr/bin/python26を設定 (N)o/(y)es/(c)ontinue: *************************************
2020-01-29 14:26:29,487 p=27650 u=tsunatori |  TASK [ansible_python_interpreter変数に/usr/bin/python26を設定] *************************************************************************
2020-01-29 14:26:29,487 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:41
2020-01-29 14:26:29,501 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:30,248 p=27650 u=tsunatori |  Perform task: TASK: SELinuxの状態を確認 (N)o/(y)es/(c)ontinue: *************************************************************************
2020-01-29 14:26:30,255 p=27650 u=tsunatori |  TASK [SELinuxの状態を確認] *************************************************************************************************************
2020-01-29 14:26:30,255 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:47
2020-01-29 14:26:30,268 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:30,888 p=27650 u=tsunatori |  Perform task: TASK: debug (N)o/(y)es/(c)ontinue: *********************************************************************************
2020-01-29 14:26:30,896 p=27650 u=tsunatori |  TASK [debug] *********************************************************************************************************************
2020-01-29 14:26:30,896 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:53
2020-01-29 14:26:30,909 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {}
2020-01-29 14:26:31,734 p=27650 u=tsunatori |  Perform task: TASK: SELinuxが無効またはAnsibleから操作可能でない場合はPlaybookを失敗させる (N)o/(y)es/(c)ontinue: ****************************************
2020-01-29 14:26:31,741 p=27650 u=tsunatori |  TASK [SELinuxが無効またはAnsibleから操作可能でない場合はPlaybookを失敗させる] ****************************************************************************
2020-01-29 14:26:31,741 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:58
2020-01-29 14:26:31,754 p=27650 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:26:31,755 p=27650 u=tsunatori |  META: ran handlers
2020-01-29 14:26:31,755 p=27650 u=tsunatori |  META: ran handlers
2020-01-29 14:26:31,761 p=27650 u=tsunatori |  PLAY [DeepSecurityエージェントのインストール] *************************************************************************************************
2020-01-29 14:26:33,367 p=27650 u=tsunatori |  Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************
2020-01-29 14:26:33,375 p=27650 u=tsunatori |  TASK [Gathering Facts] ***********************************************************************************************************
2020-01-29 14:26:33,375 p=27650 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/site.yml:33
2020-01-29 14:26:33,507 p=27650 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:26:33,508 p=27650 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:26:33,512 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:26:33,627 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:26:33,628 p=27650 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:26:33,639 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:26:33,823 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:26:36,197 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6899
2020-01-29 14:26:36,206 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:26:36,216 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:26:36,221 p=27650 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:26:36,222 p=27650 u=tsunatori |  META: ran handlers
2020-01-29 14:26:36,222 p=27650 u=tsunatori |  META: ran handlers
2020-01-29 14:26:36,223 p=27650 u=tsunatori |  META: ran handlers
2020-01-29 14:26:36,223 p=27650 u=tsunatori |  PLAY RECAP ***********************************************************************************************************************
2020-01-29 14:26:36,223 p=27650 u=tsunatori |  10.147.5.251               : ok=2    changed=0    unreachable=0    failed=0   
2020-01-29 14:52:47,995 p=29097 u=tsunatori |  ansible-playbook 2.7.0
  config file = /home/tsunatori/git/ansible/defaultdir/ansible.cfg
  configured module search path = [u'/home/tsunatori/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
2020-01-29 14:52:47,995 p=29097 u=tsunatori |  Using /home/tsunatori/git/ansible/defaultdir/ansible.cfg as config file
2020-01-29 14:52:47,995 p=29097 u=tsunatori |  setting up inventory plugins
2020-01-29 14:52:48,011 p=29097 u=tsunatori |  Parsed /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test017 inventory source with ini plugin
2020-01-29 14:52:48,105 p=29097 u=tsunatori |  statically imported: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml
2020-01-29 14:52:48,115 p=29097 u=tsunatori |  Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
2020-01-29 14:52:48,320 p=29097 u=tsunatori |  PLAYBOOK: site.yml ***************************************************************************************************************
2020-01-29 14:52:48,321 p=29097 u=tsunatori |  2 plays in site.yml
2020-01-29 14:52:48,350 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:52:48,356 p=29097 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:52:48,358 p=29097 u=tsunatori |  META: ran handlers
2020-01-29 14:52:49,981 p=29097 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:52:49,990 p=29097 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:52:49,990 p=29097 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:2
2020-01-29 14:52:50,100 p=29097 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:52:50,101 p=29097 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:52:50,106 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:52:50,286 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:52:50,288 p=29097 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:52:50,298 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:52:50,475 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:52:53,125 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:52:53,133 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:52:53,148 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:52:53,154 p=29097 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:52:54,788 p=29097 u=tsunatori |   [ERROR]: User interrupted execution

2020-01-29 14:53:04,639 p=29124 u=tsunatori |  ansible-playbook 2.7.0
  config file = /home/tsunatori/git/ansible/defaultdir/ansible.cfg
  configured module search path = [u'/home/tsunatori/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
2020-01-29 14:53:04,639 p=29124 u=tsunatori |  Using /home/tsunatori/git/ansible/defaultdir/ansible.cfg as config file
2020-01-29 14:53:04,640 p=29124 u=tsunatori |  setting up inventory plugins
2020-01-29 14:53:04,655 p=29124 u=tsunatori |  Parsed /home/tsunatori/git/ansible/defaultdir/host_vars/ymsl-test017 inventory source with ini plugin
2020-01-29 14:53:04,752 p=29124 u=tsunatori |  statically imported: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml
2020-01-29 14:53:04,763 p=29124 u=tsunatori |  Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
2020-01-29 14:53:04,967 p=29124 u=tsunatori |  PLAYBOOK: site.yml ***************************************************************************************************************
2020-01-29 14:53:04,968 p=29124 u=tsunatori |  2 plays in site.yml
2020-01-29 14:53:04,996 passlib.registry registered 'md5_crypt' handler: <class 'passlib.handlers.md5_crypt.md5_crypt'>
2020-01-29 14:53:05,003 p=29124 u=tsunatori |  PLAY [サーバ構築] *********************************************************************************************************************
2020-01-29 14:53:05,006 p=29124 u=tsunatori |  META: ran handlers
2020-01-29 14:53:06,267 p=29124 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************************
2020-01-29 14:53:06,276 p=29124 u=tsunatori |  TASK [Ansibleでsetup可能か確認] ********************************************************************************************************
2020-01-29 14:53:06,276 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:2
2020-01-29 14:53:06,385 p=29124 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:53:06,386 p=29124 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:53:06,390 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:53:06,503 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:53:06,505 p=29124 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:53:06,514 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:53:06,671 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:53:09,245 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:53:09,254 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:53:09,269 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:53:09,274 p=29124 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:53:10,099 p=29124 u=tsunatori |  Perform task: TASK: /usr/bin/python26 でセットアップ可能か確認 (N)o/(y)es/(c)ontinue: ********************************************************
2020-01-29 14:53:10,107 p=29124 u=tsunatori |  TASK [/usr/bin/python26 でセットアップ可能か確認] ********************************************************************************************
2020-01-29 14:53:10,107 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:12
2020-01-29 14:53:10,120 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:10,868 p=29124 u=tsunatori |  Perform task: TASK: redhat-releaseからバージョンを確認 (N)o/(y)es/(c)ontinue: **************************************************************
2020-01-29 14:53:10,876 p=29124 u=tsunatori |  TASK [redhat-releaseからバージョンを確認] **************************************************************************************************
2020-01-29 14:53:10,876 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:19
2020-01-29 14:53:10,889 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:11,558 p=29124 u=tsunatori |  Perform task: TASK: RHEL5系であることを確認 (N)o/(y)es/(c)ontinue: ************************************************************************
2020-01-29 14:53:11,566 p=29124 u=tsunatori |  TASK [RHEL5系であることを確認] ************************************************************************************************************
2020-01-29 14:53:11,566 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:24
2020-01-29 14:53:11,580 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:12,108 p=29124 u=tsunatori |  Perform task: TASK: EPELをインストール (N)o/(y)es/(c)ontinue: ***************************************************************************
2020-01-29 14:53:12,116 p=29124 u=tsunatori |  TASK [EPELをインストール] ***************************************************************************************************************
2020-01-29 14:53:12,116 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:28
2020-01-29 14:53:12,129 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:12,603 p=29124 u=tsunatori |  Perform task: TASK: python26をインストール (N)o/(y)es/(c)ontinue: ***********************************************************************
2020-01-29 14:53:12,611 p=29124 u=tsunatori |  TASK [python26をインストール] ***********************************************************************************************************
2020-01-29 14:53:12,611 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:35
2020-01-29 14:53:12,625 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:13,083 p=29124 u=tsunatori |  Perform task: TASK: Ansibleでsetup可能になっていることを確認 (N)o/(y)es/(c)ontinue: ************************************************************
2020-01-29 14:53:13,091 p=29124 u=tsunatori |  TASK [Ansibleでsetup可能になっていることを確認] ************************************************************************************************
2020-01-29 14:53:13,091 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:38
2020-01-29 14:53:13,105 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:13,618 p=29124 u=tsunatori |  Perform task: TASK: ansible_python_interpreter変数に/usr/bin/python26を設定 (N)o/(y)es/(c)ontinue: *************************************
2020-01-29 14:53:13,626 p=29124 u=tsunatori |  TASK [ansible_python_interpreter変数に/usr/bin/python26を設定] *************************************************************************
2020-01-29 14:53:13,626 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:41
2020-01-29 14:53:13,640 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:14,322 p=29124 u=tsunatori |  Perform task: TASK: SELinuxの状態を確認 (N)o/(y)es/(c)ontinue: *************************************************************************
2020-01-29 14:53:14,330 p=29124 u=tsunatori |  TASK [SELinuxの状態を確認] *************************************************************************************************************
2020-01-29 14:53:14,330 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:47
2020-01-29 14:53:14,344 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:15,112 p=29124 u=tsunatori |  Perform task: TASK: debug (N)o/(y)es/(c)ontinue: *********************************************************************************
2020-01-29 14:53:15,120 p=29124 u=tsunatori |  TASK [debug] *********************************************************************************************************************
2020-01-29 14:53:15,120 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:53
2020-01-29 14:53:15,134 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {}
2020-01-29 14:53:16,596 p=29124 u=tsunatori |  Perform task: TASK: SELinuxが無効またはAnsibleから操作可能でない場合はPlaybookを失敗させる (N)o/(y)es/(c)ontinue: ****************************************
2020-01-29 14:53:16,604 p=29124 u=tsunatori |  TASK [SELinuxが無効またはAnsibleから操作可能でない場合はPlaybookを失敗させる] ****************************************************************************
2020-01-29 14:53:16,604 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/import_tasks/TEST_connection.yml:58
2020-01-29 14:53:16,617 p=29124 u=tsunatori |  skipping: [10.147.5.251] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
2020-01-29 14:53:16,618 p=29124 u=tsunatori |  META: ran handlers
2020-01-29 14:53:16,618 p=29124 u=tsunatori |  META: ran handlers
2020-01-29 14:53:16,623 p=29124 u=tsunatori |  PLAY [DeepSecurityエージェントのインストール] *************************************************************************************************
2020-01-29 14:53:21,307 p=29124 u=tsunatori |  Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************
2020-01-29 14:53:21,314 p=29124 u=tsunatori |  TASK [Gathering Facts] ***********************************************************************************************************
2020-01-29 14:53:21,315 p=29124 u=tsunatori |  task path: /home/tsunatori/git/ansible/defaultdir/site.yml:34
2020-01-29 14:53:21,451 p=29124 u=tsunatori |  Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2020-01-29 14:53:21,451 p=29124 u=tsunatori |  checking if winrm_host 10.147.5.251 is an IPv6 address
2020-01-29 14:53:21,455 urllib3.connectionpool Starting new HTTPS connection (1): 10.147.5.251:5986
2020-01-29 14:53:21,567 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 1626
2020-01-29 14:53:21,569 p=29124 u=tsunatori |  EXEC (via pipeline wrapper)
2020-01-29 14:53:21,578 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 847
2020-01-29 14:53:21,755 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 753
2020-01-29 14:53:24,148 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 6903
2020-01-29 14:53:24,158 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 757
2020-01-29 14:53:24,169 urllib3.connectionpool https://10.147.5.251:5986 "POST /wsman HTTP/1.1" 200 602
2020-01-29 14:53:24,174 p=29124 u=tsunatori |  ok: [10.147.5.251]
2020-01-29 14:53:24,174 p=29124 u=tsunatori |  META: ran handlers
2020-01-29 14:53:24,175 p=29124 u=tsunatori |  META: ran handlers
2020-01-29 14:53:24,175 p=29124 u=tsunatori |  META: ran handlers
2020-01-29 14:53:24,176 p=29124 u=tsunatori |  PLAY RECAP ***********************************************************************************************************************
2020-01-29 14:53:24,176 p=29124 u=tsunatori |  10.147.5.251               : ok=2    changed=0    unreachable=0    failed=0   
